name: Selective ADF Publish for pipeline1

on:
  workflow_dispatch:
    inputs:
      StopStartTriggers:
        type: boolean
        description: 'Stop and start relevant triggers? (default: true)'
        required: false
        default: true
      DoNotStopStartExcludedTriggers:
        type: boolean
        description: 'Do not stop and start non-relevant triggers? (default: true)'
        required: false
        default: true
  push:
    paths:
      - "root/pipeline/pipeline1.json"
      - ".github/workflows/pipeline1.yaml"
      # Define additional resources that are relevant to this pipeline

env:
  pipelineName: 'pipeline1'
  rootDirectoryName: 'root'
  triggerDirectoryName: 'trigger'
  adfName: 'sqlplayer-poc'
  adfResourceGroup: 'mgb-adf-sandbox'
  location: 'eastus'

jobs:
  job_publish_pipeline:
    name: Publish-Pipeline
    runs-on: windows-latest
    environment:
      name: uat
    steps:
      - name: Install ADF dependencies
        run: |
          Install-Module -Name Az.DataFactory -MinimumVersion "1.10.0" -Force
          Install-Module -Name "azure.datafactory.tools" -Force
          Install-Module -Name Az.Resource -Force
          Import-Module -Name "azure.datafactory.tools" -Force

      - uses: actions/checkout@v3
        name: Checkout main
        with:
          ref: main
      - name: Initialize ADF Tools
        run: |
          $opt = New-AdfPublishOption
          $opt.StopStartTriggers = $true
          $opt.DoNotStopStartExcludedTriggers = $true

      - name: Retrieve relevant triggers
        run: |
          ls

          Get-ChildItem "$($env:rootDirectoryName)/$($env:triggerDirectoryName)" -Filter *.json |
          Foreach-Object {
            $content = Get-Content $_.FullName
            $jsonContent = $content | ConvertFrom-Json
            $triggerName = $jsonContent.name
            $props = $jsonContent.properties

            if ($props.pipelines  | where { $_.pipelineReference.referenceName -eq $targetPipeline }) {
                Write-Output "::debug::$($_.Name) contains $targetPipeline"
                Write-Output "::notice::Adding trigger: $triggerName to ADF publish options for stop/start"
                $opt.Includes.Add("trigger.$triggerName", "")
            }
            else {
                Write-Debug "$($_.Name) DOES NOT contain $targetPipeline"
            }    
          }
      - name: Test and Validate
        run: |
          Test-AdfCode -RootFolder "$env:rootDirectoryName"
    
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true 
      - name: Publish to ADF
        run: |
          Publish-AdfV2FromJson -RootFolder "$env:rootDirectoryName" `
            -ResourceGroupName "$env:adfResourceGroup" `
            -DataFactoryName "$env:adfName" `
            -Location "$env:location" `
            -Option $opt

